# Generated by Django 2.1.5 on 2019-01-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='article', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
