# Generated by Django 2.1.7 on 2019-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url_source',
            field=models.URLField(null=True, verbose_name='URL исходников'),
        ),
    ]
