# Generated by Django 2.1.7 on 2019-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work_url_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='short_description',
            field=models.TextField(max_length=63, verbose_name='Краткое описание'),
        ),
    ]
