# Generated by Django 2.1.5 on 2019-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190129_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.TextField(default='test', verbose_name='Превью'),
            preserve_default=False,
        ),
    ]
