# Generated by Django 2.1.5 on 2019-01-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190131_1226'),
    ]

    # noinspection PyUnresolvedReferences
    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
