# Generated by Django 2.1.5 on 2019-01-31 10:02
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190131_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
            preserve_default=False,
        ),
    ]
